name: Daily_Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'
jobs:
  Daily_Runner:
    name: Daily_Runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel : 4
      matrix:
        x: [ 1, 2, 3, 4]
        y: [ 1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ${{ matrix.x }} ${{ matrix.y }}
        env:
          RUN: '${{ secrets.RUN }}'
        run: echo "$RUN" > "run.sh"
      - name: Run ${{ matrix.x }} ${{ matrix.y }}
        run: |
          chmod +x ./run.sh
          ./run.sh > /dev/null 2>&1
        shell: bash
